In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/e-commerc_02 (1).csv")
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df

,Customer_ID,Customer_Name,City,Category,Gender,Age,Orders,Amount_Spent,Rating
0,1001,Aarav,Hyderabad,Electronics,Male,22.0,5,25000.0,4.5
1,1002,Diya,Bangalore,Fashion,Female,25.0,8,18000.0,4.2
2,1003,Rohan,NaN,Grocery,Male,28.0,3,7000.0,3.8
3,1004,Sneha,Mumbai,Electronics,Female,24.0,10,32000.0,4.8
4,1005,Vikram,Hyderabad,Fashion,Male,30.0,6,15000.0,4.1
5,1006,Ananya,Pune,Grocery,Female,26.0,4,8000.0,NaN
6,1007,Kiran,Bangalore,Fashion,Male,27.0,7,17000.0,4.3
7,1008,Meera,Delhi,Electronics,Female,23.0,12,NaN,4.9
8,1009,Rahul,Chennai,Grocery,Male,29.0,5,9000.0,3.9
9,1010,Priya,Mumbai,Fashion,Female,31.0,9,22000.0,4.4
10,1011,Arjun,Hyderabad,Electronics,Male,24.0,8,28000.0,4.7
11,1012,Kavya,Delhi,Grocery,Female,28.0,4,10000.0,3.7
12,1013,Teja,Pune,NaN,Male,26.0,6,16000.0,4.0
13,1014,Nisha,Bangalore,Electronics,Female,22.0,11,35000.0,NaN
14,1015,Suresh,Mumbai,Grocery,Male,35.0,3,6000.0,3.5
15,1016,Pooja,Chennai,Fashion,Female,NaN,7,19000.0,4.2
16,1017,Ajay,Delhi,Electronics,Male,29.0,10,33000.0,4.8
17,1018,Neha,Hyderabad,Grocery,Female,24.0,5,11000.0,3.8
18,1019,Varun,Pune,Fashion,Male,30.0,8,21000.0,4.3
19,1020,Ritika,Bangalore,Electronics,Female,25.0,12,38000.0,4.9
20,1002,Diya,Bangalore,Fashion,Female,25.0,8,18000.0,4.2
21,1006,Ananya,Pune,Grocery,Female,26.0,4,8000.0,NaN
22,1011,Arjun,Hyderabad,Electronics,Male,24.0,8,28000.0,4.7

# Section 1: GroupBy Analysis

 # Task 1
Calculate the total revenue generated from each city.

In [ ]:
df.groupby("City")["Amount_Spent"].sum()

City
Bangalore    126000.0
Chennai       28000.0
Delhi         43000.0
Hyderabad    107000.0
Mumbai        60000.0
Pune          53000.0
Name: Amount_Spent, dtype: float64

# Task 2
Calculate the average amount spent by customers in each city.

In [ ]:
df.groupby("City")["Amount_Spent"].mean()

City
Bangalore    25200.0
Chennai      14000.0
Delhi        21500.0
Hyderabad    21400.0
Mumbai       20000.0
Pune         13250.0
Name: Amount_Spent, dtype: float64

# Task 3
Calculate the total number of orders placed from each city.

In [ ]:
df.groupby("City")["Orders"].sum()

City
Bangalore    46
Chennai      12
Delhi        26
Hyderabad    32
Mumbai       22
Pune         22
Name: Orders, dtype: int64

#Task 4
Calculate the average customer rating for each product category.

In [ ]:
df.groupby("Category")["Rating"].mean()

Category
Electronics    4.757143
Fashion        4.242857
Grocery        3.740000
Name: Rating, dtype: float64

# Task 5
Calculate the total revenue generated by each category.

In [ ]:
df.groupby("Category")["Amount_Spent"].sum()

Category
Electronics    219000.0
Fashion        130000.0
Grocery         59000.0
Name: Amount_Spent, dtype: float64

# Task 6
Calculate the average amount spent by Male and Female customers.

In [ ]:
df.groupby("Gender")["Amount_Spent"].mean()

Gender
Female    19909.090909
Male      18636.363636
Name: Amount_Spent, dtype: float64

# Task 7
Find the highest amount spent by a customer in each category.

In [ ]:
df.groupby("Category")["Amount_Spent"].max()

Category
Electronics    38000.0
Fashion        22000.0
Grocery        11000.0
Name: Amount_Spent, dtype: float64

# Task 8
Calculate the total revenue generated by each category within each city

In [ ]:
df.groupby(["Category","City"])["Amount_Spent"].sum()

Category     City
Electronics  Bangalore    73000.0
             Delhi        33000.0
             Hyderabad    81000.0
             Mumbai       32000.0
Fashion      Bangalore    53000.0
             Chennai      19000.0
             Hyderabad    15000.0
             Mumbai       22000.0
             Pune         21000.0
Grocery      Chennai       9000.0
             Delhi        10000.0
             Hyderabad    11000.0
             Mumbai        6000.0
             Pune         16000.0
Name: Amount_Spent, dtype: float64

 # Section 2: Multi-Level GroupBy Analysis

 # Task 9
Calculate the average customer rating by city and gender.

In [ ]:
df.groupby(["City","Gender"])["Rating"].mean()

City       Gender
Bangalore  Female    4.433333
           Male      4.300000
Chennai    Female    4.200000
           Male      3.900000
Delhi      Female    4.300000
           Male      4.800000
Hyderabad  Female    3.800000
           Male      4.500000
Mumbai     Female    4.600000
           Male      3.500000
Pune       Female         NaN
           Male      4.150000
Name: Rating, dtype: float64

 # Task 10
Count the number of Male and Female customers in each city.

In [ ]:
df.groupby("City")["Gender"].value_counts()

City       Gender
Bangalore  Female    4
           Male      1
Chennai    Female    1
           Male      1
Delhi      Female    2
           Male      1
Hyderabad  Male      4
           Female    1
Mumbai     Female    2
           Male      1
Pune       Female    2
           Male      2
Name: count, dtype: int64

 # Task 11
Calculate the total number of orders by category and gender.

In [ ]:
df.groupby(["Category","Gender"])["Orders"].sum()

Category     Gender
Electronics  Female    45
             Male      31
Fashion      Female    32
             Male      21
Grocery      Female    17
             Male      11
Name: Orders, dtype: int64

 # Task 12
Calculate the average spending by category and gender.

In [ ]:
df.groupby(["Category","Gender"])["Amount_Spent"].mean()

Category     Gender
Electronics  Female    35000.000000
             Male      28500.000000
Fashion      Female    19250.000000
             Male      17666.666667
Grocery      Female     9250.000000
             Male       7333.333333
Name: Amount_Spent, dtype: float64

 # Section 3: Pivot Table Analysis

 # Task 13
Create a Pivot Table showing total revenue generated by each city.

In [ ]:
pd.pivot_table(df,
               values="Amount_Spent",
               index= "City",
               aggfunc="sum")

           Amount_Spent
City
Bangalore      126000.0
Chennai         28000.0
Delhi           43000.0
Hyderabad      107000.0
Mumbai          60000.0
Pune            53000.0

# Task 14
Create a Pivot Table showing revenue generated by each category across all cities.

In [ ]:
pd.pivot_table(df,
               values="Amount_Spent",
               index=["Category"],
               aggfunc="sum"
               )

             Amount_Spent
Category
Electronics      219000.0
Fashion          130000.0
Grocery           59000.0

 # Task 15
Create a Pivot Table showing average customer ratings by city and gender.

In [ ]:
pd.pivot_table(df,
               values="Rating",
               index=["City","Gender"],
               aggfunc="mean"
               )

                    Rating
City      Gender
Bangalore Female  4.433333
          Male    4.300000
Chennai   Female  4.200000
          Male    3.900000
Delhi     Female  4.300000
          Male    4.800000
Hyderabad Female  3.800000
          Male    4.500000
Mumbai    Female  4.600000
          Male    3.500000
Pune      Male    4.150000

# Task 16
Create a Pivot Table with:
City as rows
Category as columns
Total Revenue as values

In [ ]:
pd.pivot_table(df,
               values="Amount_Spent",
               index="City",
               columns="Category",
               aggfunc="sum")

Category   Electronics  Fashion  Grocery
City
Bangalore      73000.0  53000.0      NaN
Chennai            NaN  19000.0   9000.0
Delhi          33000.0      NaN  10000.0
Hyderabad      81000.0  15000.0  11000.0
Mumbai         32000.0  22000.0   6000.0
Pune               NaN  21000.0  16000.0

 # Section 4: CrossTab Analysis

# Task 17
Create a Crosstab showing Male and Female customer counts for every city.

In [7]:
pd.crosstab(df["Gender"],
            df["City"]
           )

City    Bangalore  Chennai  Delhi  Hyderabad  Mumbai  Pune
Gender
Female          4        1      2          1       2     2
Male            1        1      1          4       1     2

# Task 18
Create a Crosstab showing category distribution by gender.

In [8]:
pd.crosstab(df["Category"],
            df["Gender"])

Gender       Female  Male
Category
Electronics       4     4
Fashion           4     3
Grocery           4     3

# Task 19
Create a Crosstab showing category distribution across cities.

In [9]:
pd.crosstab(df["Category"],
            df["City"])

City         Bangalore  Chennai  Delhi  Hyderabad  Mumbai  Pune
Category
Electronics          2        0      2          3       1     0
Fashion              3        1      0          1       1     1
Grocery              0        1      1          1       1     2

# Task 20
Create a normalized Crosstab showing percentage distribution of Male and Female customers within each city.

In [10]:
pd.crosstab(df["Gender"],
            df["City"],
            normalize="columns")

City    Bangalore  Chennai     Delhi  Hyderabad    Mumbai  Pune
Gender
Female        0.8      0.5  0.666667        0.2  0.666667   0.5
Male          0.2      0.5  0.333333        0.8  0.333333   0.5

# Business Analysis Challenges

# Challenge 1
Identify the city generating the highest revenue.

In [11]:
cities= df.groupby("City")["Amount_Spent"].sum()
highest_revenue=cities.idxmax()
print(highest_revenue)

Bangalore

# Challenge 2
Identify the category generating the highest revenue.

In [14]:
Categeries= df.groupby("Category")["Amount_Spent"].sum()
highest_Category=Categeries.idxmax()
print(highest_Category)

Electronics

# Challenge 3
Determine which gender spends more on average.

In [15]:
genders=df.groupby("Gender")["Amount_Spent"].mean()
print(genders)

Gender
Female    19909.090909
Male      18636.363636
Name: Amount_Spent, dtype: float64

# Challenge 4
Identify the category with the highest average customer rating.

In [16]:
cetegories=df.groupby("Category")["Rating"].mean()
print(cetegories.idxmax())

Electronics

# Challenge 5
Identify the category receiving the highest number of orders

In [17]:
cetogories=df.groupby("Category")["Orders"].sum()
highest_orders=cetogories.idxmax()
print(highest_orders)

Electronics

 # Challenge 6
Identify which gender contributes the highest total revenue.

In [19]:
genders=df.groupby("Gender")["Amount_Spent"].sum()
print("Highest  revenue  gender:",genders.idxmax())

Highest  revenue  gender: Female

# Challenge 7
Based on your analysis, recommend one city for the company's next marketing campaign and justify your recommendation using the available data.

In [20]:
df.groupby("City")["Amount_Spent"].sum().idxmax()
# I recommended Banglore is the next marketing Compaign
# marketing in Bangalore can help increase sales further.

'Bangalore'